data = input("enter some text")
file = open("output.txt","w")
file.write(data)
file.close()
more_data= input("enter more text")
file = open("output.txt","a")
file.write("\n" + more_data)
file.close()
file = open("output.txt","r")
content = file.read()
print(content)
